// <auto-generated />
namespace MvcPot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedFullNameLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFullNameLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201703121655223_addedFullNameLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
